### ISSUE TITLE
Rename to grunt-stylefmt?

### ISSUE THREAD

**Issue by ntwb** [morishitter/grunt-stylefmt#2]
Wondering if this should be renamed to match the renamed stylefmt?

**Comment by msaktype** [comment]
Yes, I'll update it :)

**Comment by msaktype** [comment]
@ntwb I just released grunt-stylefmt v2.0.0. Please confirm it :) https://www.npmjs.com/package/grunt-stylefmt

**Comment by ntwb** [comment]
Awesome, thanks @morishitter 👍
